# fly.toml app configuration file generated for jena-fuseki on 2023-10-30T10:44:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jena-fuseki"
primary_region = "iad"

[build]

[env]
  JVM_ARGS = "-Xms1600M -Xmx1600M"

[[mounts]]
  source = "fuseki_data"
  destination = "/fuseki"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
